# Generated by Django 3.1.7 on 2021-03-06 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Photo', '0002_auto_20210306_1710'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photo',
            new_name='Gallery',
        ),
    ]
