# Generated by Django 3.1.7 on 2021-03-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Photo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
